name: Trivy Example

on:
  # trigger on pushes to main for easy testing. in reality
  # i'd probably only have this trigger from PRs against main
  push:
    branches:
      - main
    paths:
      - '**/trivy-example.yml'
      - 'trivy-testing/**'
  pull_request:
    branches:
      - main
    paths:
      - '**/trivy-example.yml'
      - 'trivy-testing/**'

permissions:
  contents: read
  packages: write # required to push to GHCR
  security-events: write # required to write Trivy findings to security events

env:
  PREVIEW_IMAGE_TAG: "ghcr.io/callum-mcgregor/nginx:preview-${{ github.sha }}"

jobs:
  build_scan_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: build Docker image
        run: |
          docker build \
            -t "$PREVIEW_IMAGE_TAG" \
            -f trivy-testing/Dockerfile \
            trivy-testing

      - name: Install Trivy
        env:
          TRIVY_VERSION: v0.72.0
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin "$TRIVY_VERSION"

      - name: Download Trivy Vulnerability DB
        run: trivy image --download-db-only

      - name: Run Trivy & output SARIF
        id: trivy-scan
        continue-on-error: true
        run: | 
          # output as JSON first (trivy convert only supports converting from JSON)
          trivy image \
            --exit-code 1 \
            --severity CRITICAL,HIGH,MEDIUM \
            --format json \
            --output trivy-results.json \
            "$PREVIEW_IMAGE_TAG"

      - name: Convert Trivy results to table and SARIF, report findings to Step Summary and Security tab
        if: always()
        run: |
          if [[ -s "trivy-results.json" ]]; then
            echo '```json' >> "$GITHUB_STEP_SUMMARY"
            trivy convert --format table trivy-results.json | tee -a "$GITHUB_STEP_SUMMARY"
            echo '```' >> "$GITHUB_STEP_SUMMARY"
            trivy convert --format sarif --output trivy-results.sarif trivy-results.json
          else
            echo "## Trivy Container Scan" >> "$GITHUB_STEP_SUMMARY"
            echo "" >> "$GITHUB_STEP_SUMMARY"
            echo "### Scan result: No vulnerabilities found" >> "$GITHUB_STEP_SUMMARY"
            echo "Image: \`$PREVIEW_IMAGE_TAG\` " >> "$GITHUB_STEP_SUMMARY"
            echo "Continuing with deployment." >> "$GITHUB_STEP_SUMMARY"
          fi

      - name: Upload Trivy results to GitHub
        if: always()
        uses: github/codeql-action/upload-sarif@codeql-bundle-v2.26.2
        with:
          sarif_file: trivy-results.sarif
          category: nginx-webserver

      - name: Fail workflow if vulnerabilities were found
        if: steps.trivy-scan.outcome == 'failure'
        run: |
          echo "::warning:: Trivy found vulnerabilities in the image. Image push blocked."
          exit 1

      - name: Log in to GHCR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_ACTOR: ${{ github.actor }}
        run: |
          echo "$GH_TOKEN" | \
          docker login ghcr.io \
            -u "$GH_ACTOR" \
            --password-stdin

      - name: Push Docker image
        run: |
          docker push "$PREVIEW_IMAGE_TAG"

  deploy:
    runs-on: ubuntu-latest
    needs: build_scan_push
    steps:
      - name: Deploy to preview
        env: 
          # here i'd use the branch name to construct a suffix to make resources unique
          # i.e., each resource in the terraform would use the below var in its name
          TF_VAR_deployment_suffix: 
          # and here i'd pass the image tag e.g., to the ECS task def to deploy the correct image
          TF_VAR_image_tag: ${{ env.PREVIEW_IMAGE_TAG }}
        run: |
          # here I would deploy a set of ephemeral infrastructure to host
          # a preview/dev application with Terraform. Given the Trivy scan is very quick
          # i'm not too worried about running this at the end of the workflow (as opposed
          # to creating the infra ASAP to avoid wasting time)
          echo "Pretending to deploy to preview"
